# before running, execute kubectl apply -f infra/k8s/db/mongo-pvc.yaml, that will create a persistent volume and persistent volume claim for mongo users db. after stopping development, execute kubectl delete -f infra/k8s/db/mongo-pvc.yaml to delete them.
# Should integrate pv and pvc with Skaffold, but for now it's just a simple yaml file.

apiVersion: skaffold/v4beta11
kind: Config
manifests:
  rawYaml:
    # - ./infra/k8s/db/*
    - ./infra/k8s/apps/*
build:
  local:
    push: false
  artifacts: 
    - image: batishchevya/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: '.'
    - image: batishchevya/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: '.'
    - image: batishchevya/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: '**/*.js'
            dest: '.'

portForward:
  - resourceType: service
    resourceName: nats-srv
    port: 4222
    localPort: 4222
  - resourceType: service
    resourceName: nats-srv
    port: 8222
    localPort: 8222
