apiVersion: skaffold/v4beta11
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts: 
    - image: batishchevya/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: '.'
    - image: batishchevya/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: '.'
    - image: batishchevya/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: '**/*.js'
            dest: '.'

portForward:
  - resourceType: service
    resourceName: nats-srv
    port: 4222
    localPort: 4222
  - resourceType: service
    resourceName: nats-srv
    port: 8222
    localPort: 8222
